# Generated by Django 4.2.5 on 2023-09-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='undefine@example.com', max_length=256),
            preserve_default=False,
        ),
    ]
